/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AttributeDialog.java
 *
 * Created on Apr 26, 2011, 2:17:23 AM
 */
package ertool;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import org.jdesktop.application.Action;

/**
 * 
 * @author Kyle
 */
public class AttributeDialog extends javax.swing.JFrame {
	private Attribute attribute;

	/** Creates new form AttributeDialog */
	public AttributeDialog() {
		initComponents();
		this.setTitle("New Attribute");
		for (Entity e : ERToolView.entities) {
			ElementChoices.add(e.getText());
		}
		for (Relationship r : ERToolView.relationships) {
			ElementChoices.add(r.getText());
		}
		TypeChoices.add(ERStore.tINT);
		TypeChoices.add(ERStore.tSTR);
		// TypeChoices.add(ERStore.tFLT);
		// TypeChoices.add(ERStore.tDBL);
	}

	public AttributeDialog(Attribute a) {
		initComponents();
		this.attribute = a;
		TypeChoices.add(ERStore.tINT);
		TypeChoices.add(ERStore.tSTR);
		this.positionCenter(ERToolView.frame);
		this.setTitle("Edit Attribute");
		for (Entity e : ERToolView.entities) {
			ElementChoices.add(e.getText());
		}
		for (Relationship r : ERToolView.relationships) {
			ElementChoices.add(r.getText());
		}
		AttributeNameField.setText(a.getText());
		ElementChoices.select(a.belongsTo.getText());
		IsKey.setState(a.isKey);
		this.TypeChoices.select(a.mLink.getType().getName());
		if (!a.mLink.getName().equals("int")) {
			ConstraintField.setVisible(true);
			ConstraintField.setText(a.mLink.getType().getConstraint() + "");
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jCheckBox1 = new javax.swing.JCheckBox();
		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		ElementChoices = new java.awt.Choice();
		TypeChoices = new java.awt.Choice();
		IsKey = new java.awt.Checkbox();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		ConstraintField = new javax.swing.JTextField();
		AttributeNameField = new javax.swing.JTextField();

		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application
				.getInstance(ertool.ERToolApp.class).getContext()
				.getResourceMap(AttributeDialog.class);
		jCheckBox1.setText(resourceMap.getString("jCheckBox1.text")); // NOI18N
		jCheckBox1.setName("jCheckBox1"); // NOI18N

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setName("Form"); // NOI18N

		jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
		jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
		jLabel1.setName("jLabel1"); // NOI18N

		jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
		jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
		jLabel3.setName("jLabel3"); // NOI18N

		jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
		jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
		jLabel4.setName("jLabel4"); // NOI18N
		jLabel4.setVisible(false);

		ElementChoices.setName("ElementChoices"); // NOI18N

		TypeChoices.setName("TypeChoices");

		IsKey.setFont(resourceMap.getFont("IsKey.font")); // NOI18N
		IsKey.setLabel(resourceMap.getString("IsKey.label")); // NOI18N
		IsKey.setName("IsKey"); // NOI18N

		javax.swing.ActionMap actionMap = org.jdesktop.application.Application
				.getInstance(ertool.ERToolApp.class).getContext()
				.getActionMap(AttributeDialog.class, this);
		TypeChoices.addItemListener(new ItemListener() {
			@Override
			public void itemStateChanged(ItemEvent item) {
				String type = item.getItem().toString();
				if (type.equals(ERStore.tSTR)) {
					jLabel4.setVisible(true);
					ConstraintField.setVisible(true);
				} else {
					jLabel4.setVisible(false);
					ConstraintField.setVisible(false);
				}
			}
		});

		jButton1.setAction(actionMap.get("createNewAttribute")); // NOI18N
		jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
		jButton1.setName("jButton1"); // NOI18N

		jButton2.setAction(actionMap.get("cancel")); // NOI18N
		jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
		jButton2.setName("jButton2"); // NOI18N

		jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
		jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
		jLabel2.setName("jLabel2"); // NOI18N

		ConstraintField.setText(resourceMap.getString("ConstraintField.text")); // NOI18N
		ConstraintField.setName("ConstraintField"); // NOI18N
		ConstraintField.setVisible(false);

		AttributeNameField.setText(resourceMap
				.getString("AttributeNameField.text")); // NOI18N
		AttributeNameField.setName("AttributeNameField"); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(186,
																		186,
																		186)
																.addComponent(
																		jButton1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		69,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(21, 21,
																		21)
																.addComponent(
																		jButton2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		82,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																				.addComponent(
																						jLabel2,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jLabel1,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jLabel3,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jLabel4,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE))
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(21,
																										21,
																										21)
																								.addComponent(
																										IsKey,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(62,
																										62,
																										62))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(18,
																										18,
																										18)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														ElementChoices,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														164,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														AttributeNameField)))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(18,
																										18,
																										18)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														TypeChoices,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														164,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														ConstraintField))))))
								.addContainerGap(21, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														AttributeNameField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1)
												.addComponent(
														ElementChoices,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel3)
												.addComponent(
														TypeChoices,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel4)
												.addComponent(
														ConstraintField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(IsKey,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton2)
												.addComponent(jButton1))
								.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new AttributeDialog().setVisible(true);
			}
		});
	}

	@Action
	public void cancel() {
		this.setVisible(false);

	}

	@Action
	public void createNewAttribute() {
		if (this.attribute == null) {
			if (isValidInput(AttributeNameField.getText())) {
				ERToolView.createAttribute(AttributeNameField.getText(), IsKey
						.getState(), ERToolView
						.findElementByName(ElementChoices.getSelectedItem()),
						TypeChoices.getSelectedItem().toString(), Integer
								.parseInt(ConstraintField.getText()));
				this.setVisible(false);
				this.dispose();
			} else {

				JOptionPane.showMessageDialog(rootPane,
						"Attribute name cannot be blank. Please try again.");

			}
		}

		else {
			if (isValidInput(AttributeNameField.getText())) {
				this.attribute.mLink.setName(AttributeNameField.getText());
				this.attribute.mLink.setIsKey(IsKey.getState());
				DraggableObject bounditem =ERToolView.findElementByName(ElementChoices.getSelectedItem());
				this.attribute.mLink.setOwner(bounditem);
				this.attribute.mLink.setType(TypeChoices.getSelectedItem().toString());
				this.attribute.mLink.setTypeConstraint(Integer.parseInt(ConstraintField.getText()));
				ERToolView.currentFocus.updateToLink();
				this.setVisible(false);
				this.dispose();
			} else {

				JOptionPane.showMessageDialog(rootPane,
						"Attribute name cannot be blank. Please try again.");

			}
		}

	}

	private boolean isValidInput(String s) {
		if (s == null || s.equals(""))
			return false;
		else if (s.charAt(0) == ' ' && s.charAt(s.length() - 1) == ' ')
			return false;
		else
			return true;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField AttributeNameField;
	private javax.swing.JTextField ConstraintField;
	private java.awt.Choice ElementChoices;
	private java.awt.Choice TypeChoices;
	private java.awt.Checkbox IsKey;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;

	// End of variables declaration//GEN-END:variables

	void positionCenter(JFrame frame) {
		this.setLocation(
				frame.getX() + (frame.getWidth() / 2) - this.getWidth() / 2,
				frame.getY() + (frame.getHeight() / 2) - this.getHeight());
	}
}
