/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EntityDialog.java
 *
 * Created on Apr 26, 2011, 1:28:23 AM
 */
package ertool;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 * 
 * @author Kyle
 */
public class EntityDialog extends javax.swing.JFrame {

	private Entity entity;

	/** Creates new form EntityDialog */

	public EntityDialog() {
		initComponents();

		this.setTitle("New Entity");

	}

	public EntityDialog(Entity e) {
		initComponents();

		this.entity = e;

		this.setTitle("Edit Entity");
		EntityNameField.setText(this.entity.getText());
		this.IsWeak.setSelected(entity.isWeak);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jDialog1 = new javax.swing.JDialog();
		jOptionPane1 = new javax.swing.JOptionPane();
		buttonGroup1 = new javax.swing.ButtonGroup();
		buttonGroup2 = new javax.swing.ButtonGroup();
		buttonGroup3 = new javax.swing.ButtonGroup();
		EntityNameField = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		OKButton = new javax.swing.JButton();
		CancelButton = new javax.swing.JButton();
		IsWeak = new javax.swing.JCheckBox();

		jDialog1.setName("jDialog1"); // NOI18N

		javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(
				jDialog1.getContentPane());
		jDialog1.getContentPane().setLayout(jDialog1Layout);
		jDialog1Layout.setHorizontalGroup(jDialog1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		jDialog1Layout.setVerticalGroup(jDialog1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));

		jOptionPane1.setName("jOptionPane1"); // NOI18N

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setName("Form"); // NOI18N

		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application
				.getInstance(ertool.ERToolApp.class).getContext()
				.getResourceMap(EntityDialog.class);
		EntityNameField.setText(resourceMap.getString("EntityNameField.text")); // NOI18N
		EntityNameField.setName("EntityNameField"); // NOI18N

		jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
		jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
		jLabel2.setName("jLabel2"); // NOI18N

		javax.swing.ActionMap actionMap = org.jdesktop.application.Application
				.getInstance(ertool.ERToolApp.class).getContext()
				.getActionMap(EntityDialog.class, this);
		OKButton.setAction(actionMap.get("createNewEntity")); // NOI18N
		OKButton.setText(resourceMap.getString("OKButton.text")); // NOI18N
		OKButton.setName("OKButton"); // NOI18N

		CancelButton.setAction(actionMap.get("cancelDialog")); // NOI18N
		CancelButton.setText(resourceMap.getString("CancelButton.text")); // NOI18N
		CancelButton.setName("CancelButton"); // NOI18N

		IsWeak.setText(resourceMap.getString("IsWeak.text")); // NOI18N
		IsWeak.setName("IsWeak"); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(39, 39, 39)
								.addComponent(jLabel2,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										90, Short.MAX_VALUE)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(IsWeak)
												.addComponent(
														EntityNameField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														232,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(31, 31, 31))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(109, 109, 109)
								.addComponent(OKButton,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										64,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(42, 42, 42).addComponent(CancelButton)
								.addContainerGap(130, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(22, 22, 22)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														EntityNameField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jLabel2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														17,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(IsWeak,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										23,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(OKButton)
												.addComponent(CancelButton))
								.addContainerGap(19, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new EntityDialog().setVisible(true);

			}
		});
	}

	@Action
	public void createNewEntity() {
		if (this.entity == null) {
			if (isValidInput(EntityNameField.getText())) {
				if (!(ERToolView.findElementByName(EntityNameField.getText())==null)){
					JOptionPane.showMessageDialog(rootPane,
					"Entity name cannot be the same as an already existing element. Please try again.");
					return;
				}
				ERToolView.createEntity(EntityNameField.getText(),
						this.IsWeak.isSelected());
				this.setVisible(false);
				this.dispose();
			} else {

				JOptionPane.showMessageDialog(rootPane,
						"Entity name cannot be blank. Please try again.");

			}
		} else {
			
			if (isValidInput(EntityNameField.getText())) {
				if (!(ERToolView.findElementByName(EntityNameField.getText())==null) && !EntityNameField.getText().equals(this.entity.getText())){
					JOptionPane.showMessageDialog(rootPane,
					"Entity name cannot be the same as an already existing element. Please try again.");
					return;
				}
				this.entity.setText(EntityNameField.getText());
				this.entity.isWeak = this.IsWeak.isSelected();

				ERToolView.currentFocus.updateFromLink();
				this.setVisible(false);

				this.dispose();
			} else {
				JOptionPane.showMessageDialog(rootPane,
						"Entity name cannot be blank. Please try again.");
				
			}

		}

	}

	public void positionCenter(JFrame frame) {
		this.setLocation(
				frame.getX() + (frame.getWidth() / 2) - this.getWidth() / 2,
				frame.getY() + (frame.getHeight() / 2) - this.getHeight());
	}

	@Action
	public void cancelDialog() {
		this.setVisible(false);
	}

	private boolean isValidInput(String s) {
		if (s == null || s.equals(""))
			return false;
		else if (s.charAt(0) == ' ' && s.charAt(s.length() - 1) == ' ')
			return false;
		else
			return true;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton CancelButton;
	private javax.swing.JTextField EntityNameField;
	private javax.swing.JCheckBox IsWeak;
	private javax.swing.JButton OKButton;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.ButtonGroup buttonGroup2;
	private javax.swing.ButtonGroup buttonGroup3;
	private javax.swing.JDialog jDialog1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JOptionPane jOptionPane1;
	// End of variables declaration//GEN-END:variables

}
