/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RelationShipDialog.java
 *
 * Created on Apr 26, 2011, 3:32:12 AM
 */
package ertool;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author Kyle
 */
public class RelationShipDialog extends javax.swing.JFrame {
	private Relationship relationship;

    /** Creates new form RelationShipDialog */
    public RelationShipDialog() {
        initComponents();
        this.setTitle("New Relationship");
        for (Entity e: ERToolView.entities){
            EntityChoice1.add(e.getText());
        }
        for (Entity e: ERToolView.entities){
                   if (!EntityChoice1.getSelectedItem().equals(e.getText())){
                       EntityChoice2.add(e.getText());
                   }
               }
       
        EntityChoice1.addItemListener(new ItemListener() {

            ///when a different first entity is selected, make sure that it can't also be selected as the second entity
            
            public void itemStateChanged(ItemEvent arg0) {
               EntityChoice2.removeAll();
               for (Entity e: ERToolView.entities){
                   if (!EntityChoice1.getSelectedItem().equals(e.getText())){
                       EntityChoice2.add(e.getText());
                   }
               }
            }
        });
    }
    
    public RelationShipDialog(Relationship r) {
        initComponents();
        this.relationship = r;
        this.setTitle("Edit Relationship");
        for (Entity e: ERToolView.entities){
            EntityChoice1.add(e.getText());
        }
        this.RelationshipNameField.setText(this.relationship.getText());
        this.EntityChoice1.select(this.relationship.firstEntity.getText());
        
        for (Entity e: ERToolView.entities){
                   if (!EntityChoice1.getSelectedItem().equals(e.getText())){
                       EntityChoice2.add(e.getText());
                   }
               }
        this.EntityChoice2.select(this.relationship.secondEntity.getText());
        
        EntityChoice1.addItemListener(new ItemListener() {

            ///when a different first entity is selected, make sure that it can't also be selected as the second entity
            
            public void itemStateChanged(ItemEvent arg0) {
               EntityChoice2.removeAll();
               for (Entity e: ERToolView.entities){
                   if (!EntityChoice1.getSelectedItem().equals(e.getText())){
                       EntityChoice2.add(e.getText());
                   }
               }
            }
        });
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RelationshipNameField = new javax.swing.JTextField();
        EntityChoice1 = new java.awt.Choice();
        EntityChoice2 = new java.awt.Choice();
        OKButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ertool.ERToolApp.class).getContext().getResourceMap(RelationShipDialog.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        RelationshipNameField.setText(resourceMap.getString("RelationshipNameField.text")); // NOI18N
        RelationshipNameField.setName("RelationshipNameField"); // NOI18N
        RelationshipNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelationshipNameFieldActionPerformed(evt);
            }
        });

        EntityChoice1.setName("EntityChoice1"); // NOI18N

        EntityChoice2.setName("EntityChoice2"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ertool.ERToolApp.class).getContext().getActionMap(RelationShipDialog.class, this);
        OKButton.setAction(actionMap.get("createNewRelationship")); // NOI18N
        OKButton.setText(resourceMap.getString("OKButton.text")); // NOI18N
        OKButton.setName("OKButton"); // NOI18N

        jButton2.setAction(actionMap.get("cancel")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RelationshipNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(EntityChoice2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EntityChoice1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(RelationshipNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EntityChoice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EntityChoice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKButton)
                    .addComponent(jButton2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RelationshipNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelationshipNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelationshipNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RelationShipDialog().setVisible(true);
            }
        });
    }

    @Action
    public void cancel() {
        this.setVisible(false);
    }

    @Action
    public void createNewRelationship() {
    	if (this.relationship ==null){
         if (isValidInput(RelationshipNameField.getText())){
            ERToolView.createRelationship(RelationshipNameField.getText(),(Entity) ERToolView.findElementByName(EntityChoice1.getSelectedItem()),(Entity)  ERToolView.findElementByName(EntityChoice2.getSelectedItem()));
            this.setVisible(false);
            this.dispose();
        }
        else{
            
            JOptionPane.showMessageDialog(rootPane, "Relationship name cannot be blank. Please try again.");
           
           
        }
    	}
    	else{
    		if (isValidInput(RelationshipNameField.getText())){
    			this.relationship.removeEntities();
    			
    			this.relationship.mLink.setFirstOwner((Entity) ERToolView.findElementByName(EntityChoice1.getSelectedItem()));
    			this.relationship.mLink.setSecondOwner((Entity) ERToolView.findElementByName(EntityChoice2.getSelectedItem()));
    			this.relationship.mLink.setName(RelationshipNameField.getText());
    			
    			ERToolView.currentFocus.updateToLink();
    			
    			this.relationship.firstEntity.relationships.add(this.relationship);
    			this.relationship.secondEntity.relationships.add(this.relationship);
    			
    			ERToolView.currentFocus.updateToLink();
                
                this.setVisible(false);
                this.dispose();
            }
            else{
                
                JOptionPane.showMessageDialog(rootPane, "Relationship name cannot be blank. Please try again.");
    	}
    	}
        
        
        
    }
    
    private boolean isValidInput(String s){
        if (s==null || s.equals("")) return false;
        else if (s.charAt(0)==' ' && s.charAt(s.length()-1)==' ') return false; 
        else return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice EntityChoice1;
    private java.awt.Choice EntityChoice2;
    private javax.swing.JButton OKButton;
    private javax.swing.JTextField RelationshipNameField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    void positionCenter(JFrame frame) {
        this.setLocation(frame.getX()+(frame.getWidth()/2)-this.getWidth()/2,frame.getY()+(frame.getHeight()/2)-this.getHeight());
    }
}
